name: Publish to PyPI

on:
  push:
    tags:  # Trigger the workflow only on tag pushes
      - "*"  # Match all tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')  # Only run on tag pushes

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install build dependencies
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine setuptools wheel setuptools-scm  # Added setuptools-scm

      # Step 4: Build the distribution
      - name: Build the package
        run: python setup.py sdist bdist_wheel  # Use setup.py

      # Step 5: Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload dist/*