name: Run Tests on Push

# Trigger this workflow on push to any branch
on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Replace with the version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt for all dependencies
          pip install pytest coverage  # Make sure pytest and coverage are installed

      # Run tests
      - name: Run test script
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Optional: limit test failures and suppress warnings for a clean output

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          coverage run -m pytest  # Run tests with coverage
          coverage report -m  # Show coverage results in the terminal
          coverage html -d coverage_html_report  # Optional: Generate HTML report for better coverage insight
          ls coverage_html_report  # Optional: List the contents of the HTML report directory

      # Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
