name: Run Tests on Push

# Trigger this workflow on push to any branch
on:
  push:
    branches:
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # or the version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      # Run tests
      - name: Run test script
        run: |
          pytest .
      - name: Run tests with coverage
        run: |
          pip install coverage
          coverage run -m pytest  # Run tests with coverage
          coverage report -m  # Show coverage results in the terminal

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub
